CREATE TABLE [dbo].[Baskets]
(
	[ID] INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_Baskets PRIMARY KEY,
	[UID] UNIQUEIDENTIFIER NOT NULL,
	[CreatedAt] DATETIME2(0) NOT NULL CONSTRAINT df_Baskets_CreatedAt DEFAULT GETDATE()
)